batch_size: 64
iters: 2000

train_dataset:
  type: ADE20K
  dataset_root: test_tipc/data/ADEChallengeData2016
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.5
      max_scale_factor: 2.0
      scale_step_size: 0.25
    - type: RandomPaddingCrop
      crop_size: [520, 520]
      im_padding_value: [0, 0, 0]
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.4
      contrast_range: 0.4
      saturation_range: 0.4
    - type: Normalize
  mode: train

val_dataset:
  type: ADE20K
  dataset_root: test_tipc/data/ADEChallengeData2016
  transforms:
    - type: Normalize
  mode: val

export:
  transforms:
    - type: Normalize


optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 0.0005

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.01
  end_lr: 0
  power: 0.9

loss:
  types:
    - type: CrossEntropyLoss # output
    - type: CrossEntropyLoss # fcn out
    - type: SeCrossEntropyLoss # se out
      num_classes: 150
  coef: [1, 0.4, 0.2]

model:
  type: FastFCN
  backbone:
    type: ResNet50_vd
    output_stride: 8
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/resnet50_vd_ssld_v2.tar.gz
  num_codes: 32
  mid_channels: 512
  jpu: True
  aux_loss: True
  use_se_loss: True
  add_lateral: True
