batch_size: 2
iters: 80000

train_dataset:
  type: Dataset
  dataset_root: test_tipc/data/cityscapes
  train_path: test_tipc/data/cityscapes/test.list
  num_classes: 19
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.5
      max_scale_factor: 2.0
      scale_step_size: 0.25
    - type: RandomPaddingCrop
      crop_size: [1024, 512]
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.4
      contrast_range: 0.4
      saturation_range: 0.4
    - type: Normalize
  mode: train

val_dataset:
  type: Dataset
  dataset_root: test_tipc/data/cityscapes
  val_path: test_tipc/data/cityscapes/val.list
  num_classes: 19
  transforms:
    - type: Normalize
  mode: val

export:
  transforms:
    - type: Resize
      target_size: [512, 512]
    - type: Normalize

model:
  type: ENCNet
  backbone:
    type: ResNet101_vd
    output_stride: 8
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/resnet101_vd_ssld.tar.gz
  num_codes: 32
  mid_channels: 512
  up_scale: 8
  in_index: [1, 2, 3]
  use_se_loss: True
  add_lateral: True
  pretrained: test_tipc/output/encnet_small/model.pdparams

optimizer:
  type: sgd
  weight_decay: 0.0005

loss:
  types:
    - type: CrossEntropyLoss # output
    - type: CrossEntropyLoss # fcn out
    - type: SeCrossEntropyLoss # se out
      num_classes: 19
  coef: [1, 0.4, 0.2]

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.01
  end_lr: 0.0
  power: 0.9
