iters: 80000
batch_size: 8

train_dataset:
  type: Cityscapes
  dataset_root: data/cityscapes
  transforms:
    - type: RandomPaddingCrop
      crop_size: [1024, 512]
    - type: RandomDistort
      brightness_range: 0.4
      contrast_range: 0.4
      saturation_range: 0.4
    - type: Normalize
  mode: train

val_dataset:
  type: Cityscapes
  dataset_root: data/cityscapes
  transforms:
    - type: Normalize
  mode: val

model:
  type: ENet
  num_classes: 19
  pretrained: Null

optimizer:
  type: adam
  weight_decay: 0.0002

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.001
  end_lr: 0
  power: 0.9

loss:
  types:
    - type: CrossEntropyLoss
  coef: [1]
